IMG_HEIGHT = 224
IMG_WIDTH = 224
IMG_CHANNELS = 3
DEFAULT_SEQ_LENGTH = 20
MANIPULATION_LENGTH = 3
NUMBER_OF_SUBSEQUENCES = 2
AVG_DISTANCE_BETWEEN_SUBSEQUENCES = 1
AVG_LENGTH_OF_SUBSEQUENCES = 1
FILE_LIMIT = 100
MIN_SEQ_LENGTH = 40
MAX_SEQ_LENGTH = 300

